### ISSUE TITLE
Section_5_Docker_Compose-Exercise_1

### ISSUE THREAD

**Issue by gabriel-delarosa** [mmumshad/docker-training-answer-keys#3]
docker-compose.yml - Check Solution needs to be updated to match with the task:

Task: Add a new service(tier) named "**wordpress_db**" to the docker-compose.yml file use the image "**mysql**"

if you add below service it fails as is expecting to match the service **mysql** instead of **wordpress_db**

version: '3'
services:
  web:
      image: "wordpress"

  wordpress_db:
      image: "mysql"

**Comment by mmumshad** [comment]
Sorry just fixed it. Should be mysql
